/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the authenticated owner's buildings (unmasked coordinates) */
        get: operations["ListBuildings"];
        put?: never;
        /** @description Register a new building */
        post: operations["RegisterBuilding"];
        delete?: never;
        options?: never;
        /** @description List the authenticated owner's buildings (unmasked coordinates) */
        head: operations["ListBuildings"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a building by ID */
        get: operations["GetBuildingById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Get a building by ID */
        head: operations["GetBuildingById"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a building by slug */
        get: operations["GetBuildingBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Get a building by slug */
        head: operations["GetBuildingBySlug"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new building name effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeBuildingName"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new building address effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeBuildingAddress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new building type effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeBuildingType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new building location effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeBuildingLocation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record new construction/renovation years effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeBuildingYears"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the rooms of a building the caller owns */
        get: operations["ListRooms"];
        put?: never;
        /** @description Register a new room in a building */
        post: operations["RegisterRoom"];
        delete?: never;
        options?: never;
        /** @description List the rooms of a building the caller owns */
        head: operations["ListRooms"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a room by ID */
        get: operations["GetRoomById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Get a room by ID */
        head: operations["GetRoomById"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a room by slug */
        get: operations["GetRoomBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Get a room by slug */
        head: operations["GetRoomBySlug"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new room name effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeRoomName"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/floor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new room floor effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeRoomFloor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/function": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new room function effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeRoomFunction"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/exposure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new room exposure effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeRoomExposure"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record new room geometry (area, ceiling height) effective from validFrom (appends history) */
        put: operations["ChangeRoomGeometry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/ventilation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new room ventilation type effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeRoomVentilation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/pollution-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Record a pollution source effective from validFrom (appends history) */
        post: operations["AddPollutionSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/pollution-sources/{sourceCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Close a pollution source's validity as of validTo (soft history) */
        put: operations["RemovePollutionSource"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the sensors of a room in a building the caller owns */
        get: operations["ListSensors"];
        put?: never;
        /** @description Register a new sensor in a room */
        post: operations["RegisterSensor"];
        delete?: never;
        options?: never;
        /** @description List the sensors of a room in a building the caller owns */
        head: operations["ListSensors"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a sensor by ID */
        get: operations["GetSensorById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Get a sensor by ID */
        head: operations["GetSensorById"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a sensor by slug */
        get: operations["GetSensorBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Get a sensor by slug */
        head: operations["GetSensorBySlug"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record new sensor identity (manufacturer, model, serial) effective from validFrom (appends history) */
        put: operations["ChangeSensorIdentity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}/placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new sensor placement (room) effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeSensorPlacement"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record a new sensor lifecycle status effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeSensorStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}/installation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Record new sensor installation details (F08) effective from validFrom (appends history, does not overwrite) */
        put: operations["ChangeSensorInstallation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}/measured-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Record a measured-parameter capability effective from validFrom (appends history) */
        post: operations["AddMeasuredParameter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms/{roomId}/sensors/{sensorId}/measured-parameters/{parameterCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Close a measured-parameter capability's validity as of validTo (soft history) */
        put: operations["RemoveMeasuredParameter"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/address-lookup/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Autocomplete Czech addresses against RÚIAN (ČÚZK, CC BY 4.0) */
        get: operations["SuggestAddresses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/address-lookup/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Resolve a suggestion key to the full OFN address (RÚIAN codes + WGS84 coordinates) */
        get: operations["ResolveAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMeasuredParameterRequest: {
            parameterCode: string;
            /** Format: date-time */
            validFrom: string;
        };
        AddPollutionSourceRequest: {
            sourceCode: string;
            /** Format: date-time */
            validFrom: string;
        };
        AddressSuggestion: {
            text: string;
            key: string;
        };
        AddressSuggestionsResponse: {
            suggestions: components["schemas"]["AddressSuggestion"][];
        };
        BuildingSnapshotResponse: {
            /** Format: uuid */
            id: string;
            uriSlug: string;
            /** Format: uuid */
            ownerId: string;
            name: string;
            /** Format: int64 */
            addressPointCode: number | string;
            streetName: null | string;
            /** Format: int32 */
            houseNumber: number | string;
            houseNumberType: string;
            /** Format: int32 */
            orientationNumber: null | number | string;
            orientationNumberLetter: null | string;
            municipalityName: string;
            municipalityPartName: null | string;
            psc: string;
            districtName: null | string;
            regionName: null | string;
            /** Format: int64 */
            streetCode: null | number | string;
            /** Format: int64 */
            municipalityCode: null | number | string;
            /** Format: int64 */
            municipalityPartCode: null | number | string;
            /** Format: int64 */
            districtCode: null | number | string;
            /** Format: int64 */
            regionCode: null | number | string;
            buildingTypeCode: string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: int16 */
            yearBuilt: null | number | string;
            /** Format: int16 */
            yearRenovated: null | number | string;
            /** Format: date-time */
            asOf: string;
        };
        ChangeBuildingAddressRequest: {
            /** Format: int64 */
            addressPointCode: number | string;
            streetName: null | string;
            /** Format: int32 */
            houseNumber: number | string;
            houseNumberType: string;
            /** Format: int32 */
            orientationNumber: null | number | string;
            orientationNumberLetter: null | string;
            municipalityName: string;
            municipalityPartName: null | string;
            psc: string;
            districtName: null | string;
            regionName: null | string;
            /** Format: date-time */
            validFrom: string;
            /** Format: int64 */
            streetCode?: null | number | string;
            /** Format: int64 */
            municipalityCode?: null | number | string;
            /** Format: int64 */
            municipalityPartCode?: null | number | string;
            /** Format: int64 */
            districtCode?: null | number | string;
            /** Format: int64 */
            regionCode?: null | number | string;
        };
        ChangeBuildingLocationRequest: {
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeBuildingNameRequest: {
            newName: string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeBuildingTypeRequest: {
            newTypeCode: string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeBuildingYearsRequest: {
            /** Format: int16 */
            yearBuilt: null | number | string;
            /** Format: int16 */
            yearRenovated: null | number | string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeRoomAttributeRequest: {
            newValue: string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeRoomFloorRequest: {
            /** Format: uint8 */
            floor: number | string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeRoomGeometryRequest: {
            /** Format: double */
            areaM2: null | number | string;
            /** Format: double */
            ceilingHeightM: null | number | string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeSensorIdentityRequest: {
            manufacturer: string;
            model: string;
            serialNumber: string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeSensorInstallationRequest: {
            positionNote: null | string;
            /** Format: double */
            distanceWindowM: null | number | string;
            /** Format: double */
            distanceDoorM: null | number | string;
            /** Format: double */
            distanceSourceM: null | number | string;
            /** Format: int32 */
            measurementFrequencySeconds: null | number | string;
            /** Format: date */
            installedOn: null | string;
            /** Format: date */
            lastCalibratedOn: null | string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeSensorPlacementRequest: {
            /** Format: uuid */
            newRoomId: string;
            /** Format: date-time */
            validFrom: string;
        };
        ChangeSensorStatusRequest: {
            newStatusCode: string;
            /** Format: date-time */
            validFrom: string;
        };
        MeasuredParameterResponse: {
            code: string;
            quantityKindUri: null | string;
            unitUri: null | string;
        };
        RegisterBuildingRequest: {
            name: string;
            /** Format: int64 */
            addressPointCode: number | string;
            streetName: null | string;
            /** Format: int32 */
            houseNumber: number | string;
            houseNumberType: string;
            /** Format: int32 */
            orientationNumber: null | number | string;
            orientationNumberLetter: null | string;
            municipalityName: string;
            municipalityPartName: null | string;
            psc: string;
            districtName: null | string;
            regionName: null | string;
            buildingTypeCode: string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: int16 */
            yearBuilt: null | number | string;
            /** Format: int16 */
            yearRenovated: null | number | string;
            /** Format: int64 */
            streetCode?: null | number | string;
            /** Format: int64 */
            municipalityCode?: null | number | string;
            /** Format: int64 */
            municipalityPartCode?: null | number | string;
            /** Format: int64 */
            districtCode?: null | number | string;
            /** Format: int64 */
            regionCode?: null | number | string;
        };
        RegisterBuildingResult: {
            /** Format: uuid */
            id: string;
            uriSlug: string;
        };
        RegisterRoomRequest: {
            name: string;
            /** Format: uint8 */
            floor: number | string;
            functionCode: null | string;
            exposureCode: null | string;
            /** Format: double */
            areaM2: null | number | string;
            /** Format: double */
            ceilingHeightM: null | number | string;
            ventilationType: null | string;
            pollutionSources: string[];
        };
        RegisterSensorRequest: {
            manufacturer: string;
            model: string;
            serialNumber: string;
            statusCode: string;
            measuredParameters: string[];
            installation?: null | components["schemas"]["SensorInstallationRequest"];
        };
        RemoveMeasuredParameterRequest: {
            /** Format: date-time */
            validTo: string;
        };
        RemovePollutionSourceRequest: {
            /** Format: date-time */
            validTo: string;
        };
        ResolvedAddress: {
            /** Format: int64 */
            addressPointCode: number | string;
            streetName: null | string;
            /** Format: int32 */
            houseNumber: number | string;
            houseNumberType: string;
            /** Format: int32 */
            orientationNumber: null | number | string;
            orientationNumberLetter: null | string;
            municipalityName: string;
            municipalityPartName: null | string;
            psc: string;
            districtName: null | string;
            regionName: null | string;
            /** Format: int64 */
            streetCode: null | number | string;
            /** Format: int64 */
            municipalityCode: null | number | string;
            /** Format: int64 */
            municipalityPartCode: null | number | string;
            /** Format: int64 */
            districtCode: null | number | string;
            /** Format: int64 */
            regionCode: null | number | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            text: string;
        };
        RoomSnapshotResponse: {
            /** Format: uuid */
            id: string;
            uriSlug: string;
            /** Format: uuid */
            buildingId: string;
            name: string;
            /** Format: uint8 */
            floor: number | string;
            functionCode: null | string;
            exposureCode: null | string;
            /** Format: double */
            areaM2: null | number | string;
            /** Format: double */
            ceilingHeightM: null | number | string;
            ventilationType: null | string;
            pollutionSources: string[];
            /** Format: date-time */
            asOf: string;
        };
        SensorInstallationRequest: {
            positionNote: null | string;
            /** Format: double */
            distanceWindowM: null | number | string;
            /** Format: double */
            distanceDoorM: null | number | string;
            /** Format: double */
            distanceSourceM: null | number | string;
            /** Format: int32 */
            measurementFrequencySeconds: null | number | string;
            /** Format: date */
            installedOn: null | string;
            /** Format: date */
            lastCalibratedOn: null | string;
        };
        SensorInstallationResponse: {
            positionNote: null | string;
            /** Format: double */
            distanceWindowM: null | number | string;
            /** Format: double */
            distanceDoorM: null | number | string;
            /** Format: double */
            distanceSourceM: null | number | string;
            /** Format: int32 */
            measurementFrequencySeconds: null | number | string;
            /** Format: date */
            installedOn: null | string;
            /** Format: date */
            lastCalibratedOn: null | string;
        };
        SensorRegisteredResponse: {
            /** Format: uuid */
            id: string;
            uriSlug: string;
            /** Format: uuid */
            buildingId: string;
            /** Format: uuid */
            roomId: string;
            manufacturer: string;
            model: string;
            serialNumber: string;
            statusCode: string;
            measuredParameters: components["schemas"]["MeasuredParameterResponse"][];
            installation: null | components["schemas"]["SensorInstallationResponse"];
            /** Format: date-time */
            asOf: string;
            apiKey: string;
        };
        SensorSnapshotResponse: {
            /** Format: uuid */
            id: string;
            uriSlug: string;
            /** Format: uuid */
            buildingId: string;
            /** Format: uuid */
            roomId: string;
            manufacturer: string;
            model: string;
            serialNumber: string;
            statusCode: string;
            measuredParameters: components["schemas"]["MeasuredParameterResponse"][];
            installation: null | components["schemas"]["SensorInstallationResponse"];
            /** Format: date-time */
            asOf: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSnapshotResponse"][];
                };
            };
        };
    };
    RegisterBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBuildingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterBuildingResult"];
                };
            };
        };
    };
    ListBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSnapshotResponse"][];
                };
            };
        };
    };
    GetBuildingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBuildingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBuildingBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBuildingBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeBuildingName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeBuildingNameRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeBuildingAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeBuildingAddressRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeBuildingType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeBuildingTypeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeBuildingLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeBuildingLocationRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeBuildingYears: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeBuildingYearsRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"][];
                };
            };
        };
    };
    RegisterRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRoomRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"];
                };
            };
        };
    };
    ListRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"][];
                };
            };
        };
    };
    GetRoomById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRoomById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRoomBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRoomBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeRoomName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoomAttributeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeRoomFloor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoomFloorRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeRoomFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoomAttributeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeRoomExposure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoomAttributeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeRoomGeometry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoomGeometryRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeRoomVentilation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoomAttributeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddPollutionSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPollutionSourceRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemovePollutionSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sourceCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemovePollutionSourceRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListSensors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorSnapshotResponse"][];
                };
            };
        };
    };
    RegisterSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSensorRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorRegisteredResponse"];
                };
            };
        };
    };
    ListSensors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorSnapshotResponse"][];
                };
            };
        };
    };
    GetSensorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetSensorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetSensorBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetSensorBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeSensorIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSensorIdentityRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeSensorPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSensorPlacementRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeSensorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSensorStatusRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangeSensorInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSensorInstallationRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddMeasuredParameter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMeasuredParameterRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveMeasuredParameter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
                roomId: string;
                sensorId: string;
                parameterCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveMeasuredParameterRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuggestAddresses: {
        parameters: {
            query?: {
                q?: string;
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressSuggestionsResponse"];
                };
            };
        };
    };
    ResolveAddress: {
        parameters: {
            query?: {
                key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedAddress"];
                };
            };
        };
    };
}
