/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/observations/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate observations into buckets + distribution
         * @description Server-side aggregation for the map's click-through chart. Either buildingId (aggregate across the building's sensors) or sensorId (one sensor) is required, plus parameterCode. Filters: from, to (ISO-8601), bucket (auto|5m|1h|6h|1d|1w). bucket=auto picks a granularity from the span and caps the bucket count.
         */
        get: operations["AggregateObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Aggregate observations into buckets + distribution
         * @description Server-side aggregation for the map's click-through chart. Either buildingId (aggregate across the building's sensors) or sensorId (one sensor) is required, plus parameterCode. Filters: from, to (ISO-8601), bucket (auto|5m|1h|6h|1d|1w). bucket=auto picks a granularity from the span and caps the bucket count.
         */
        head: operations["AggregateObservations"];
        patch?: never;
        trace?: never;
    };
    "/v1/observations.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export observations as CSV
         * @description Streams the filtered observation set as a downloadable CSV archive (CC BY 4.0).
         */
        get: operations["ExportObservationsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Export observations as CSV
         * @description Streams the filtered observation set as a downloadable CSV archive (CC BY 4.0).
         */
        head: operations["ExportObservationsCsv"];
        patch?: never;
        trace?: never;
    };
    "/v1/context/measurements.jsonld": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JSON-LD context for observations
         * @description The @context document that observation JSON-LD responses link to.
         */
        get: operations["GetMeasurementsContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * JSON-LD context for observations
         * @description The @context document that observation JSON-LD responses link to.
         */
        head: operations["GetMeasurementsContext"];
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DCAT-AP 3.0 catalog metadata
         * @description Open-data catalog record describing the IEQ dataset (JSON-LD / JSON).
         */
        get: operations["GetDcatCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * DCAT-AP 3.0 catalog metadata
         * @description Open-data catalog record describing the IEQ dataset (JSON-LD / JSON).
         */
        head: operations["GetDcatCatalog"];
        patch?: never;
        trace?: never;
    };
    "/v1/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List observations
         * @description Keyset-paginated measurements as SSN/SOSA observations. Filters: from, to, sensorId, parameterCode, buildingId, roomId, bbox, includeInvalid, limit, cursor. Negotiates application/json (default), application/ld+json, and text/csv. Paging is keyset (opaque cursor), not offset: the observations hypertable is append-only and unbounded, so a cursor gives stable, gap-free pages and constant latency at any depth — unlike the catalog endpoints, which use small, bounded offset/page collections.
         */
        get: operations["ListObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * List observations
         * @description Keyset-paginated measurements as SSN/SOSA observations. Filters: from, to, sensorId, parameterCode, buildingId, roomId, bbox, includeInvalid, limit, cursor. Negotiates application/json (default), application/ld+json, and text/csv. Paging is keyset (opaque cursor), not offset: the observations hypertable is append-only and unbounded, so a cursor gives stable, gap-free pages and constant latency at any depth — unlike the catalog endpoints, which use small, bounded offset/page collections.
         */
        head: operations["ListObservations"];
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an observation by id
         * @description The stable IRI target for a single observation (JSON or JSON-LD).
         */
        get: operations["GetObservationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get an observation by id
         * @description The stable IRI target for a single observation (JSON or JSON-LD).
         */
        head: operations["GetObservationById"];
        patch?: never;
        trace?: never;
    };
    "/v1/map/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest-value building markers for a quantity
         * @description One marker per building with ≥1 active sensor measuring parameterCode. latestValue is the mean of each sensor's most-recent value; stale markers (freshest observation older than the freshness window) carry a null latestValue. Filters: parameterCode (required), bbox (minLon,minLat,maxLon,maxLat). Cached ~60 s.
         */
        get: operations["GetMapSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Latest-value building markers for a quantity
         * @description One marker per building with ≥1 active sensor measuring parameterCode. latestValue is the mean of each sensor's most-recent value; stale markers (freshest observation older than the freshness window) carry a null latestValue. Filters: parameterCode (required), bbox (minLon,minLat,maxLon,maxLat). Cached ~60 s.
         */
        head: operations["GetMapSnapshot"];
        patch?: never;
        trace?: never;
    };
    "/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List observable properties
         * @description The platform's IEQ observable-property vocabulary. Each entry is the sosa:observedProperty target for its parameter, with its QUDT quantity kind + applicable unit and any authoritative external match. JSON or JSON-LD.
         */
        get: operations["ListProperties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * List observable properties
         * @description The platform's IEQ observable-property vocabulary. Each entry is the sosa:observedProperty target for its parameter, with its QUDT quantity kind + applicable unit and any authoritative external match. JSON or JSON-LD.
         */
        head: operations["ListProperties"];
        patch?: never;
        trace?: never;
    };
    "/v1/properties/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an observable property by code
         * @description The dereferenceable IRI target for a single observed property (JSON or JSON-LD).
         */
        get: operations["GetPropertyByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get an observable property by code
         * @description The dereferenceable IRI target for a single observed property (JSON or JSON-LD).
         */
        head: operations["GetPropertyByCode"];
        patch?: never;
        trace?: never;
    };
    "/v1/codelists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List codelists
         * @description The catalog's controlled vocabularies as SKOS concept schemes (JSON or JSON-LD).
         */
        get: operations["ListCodelists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * List codelists
         * @description The catalog's controlled vocabularies as SKOS concept schemes (JSON or JSON-LD).
         */
        head: operations["ListCodelists"];
        patch?: never;
        trace?: never;
    };
    "/v1/codelists/{scheme}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a codelist (concept scheme)
         * @description A single codelist with its bilingual concepts (JSON or JSON-LD).
         */
        get: operations["GetCodelistScheme"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get a codelist (concept scheme)
         * @description A single codelist with its bilingual concepts (JSON or JSON-LD).
         */
        head: operations["GetCodelistScheme"];
        patch?: never;
        trace?: never;
    };
    "/v1/codelists/{scheme}/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a codelist concept
         * @description The dereferenceable IRI target for a single codelist concept (JSON or JSON-LD).
         */
        get: operations["GetCodelistConcept"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get a codelist concept
         * @description The dereferenceable IRI target for a single codelist concept (JSON or JSON-LD).
         */
        head: operations["GetCodelistConcept"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List buildings
         * @description Filters: buildingType, bbox (minLon,minLat,maxLon,maxLat), page, pageSize. Offset/page paged with a total count: the catalog is small and bounded, so a page index is friendlier than the keyset cursor used by the unbounded observations feed. Each building carries a Czech OFN address (see the Address schema). Negotiable as JSON (default) or JSON-LD (Accept: application/ld+json).
         */
        get: operations["ListBuildings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * List buildings
         * @description Filters: buildingType, bbox (minLon,minLat,maxLon,maxLat), page, pageSize. Offset/page paged with a total count: the catalog is small and bounded, so a page index is friendlier than the keyset cursor used by the unbounded observations feed. Each building carries a Czech OFN address (see the Address schema). Negotiable as JSON (default) or JSON-LD (Accept: application/ld+json).
         */
        head: operations["ListBuildings"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a building by id
         * @description Returns one building with its current OFN address (see the Address schema) and precise coordinates. Negotiable as JSON (default) or JSON-LD; the JSON-LD form emits a conformant OFN Adresa node with dereferenceable RÚIAN IRIs.
         */
        get: operations["GetBuildingById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get a building by id
         * @description Returns one building with its current OFN address (see the Address schema) and precise coordinates. Negotiable as JSON (default) or JSON-LD; the JSON-LD form emits a conformant OFN Adresa node with dereferenceable RÚIAN IRIs.
         */
        head: operations["GetBuildingById"];
        patch?: never;
        trace?: never;
    };
    "/v1/buildings/{buildingId}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List rooms of a building
         * @description Filters: roomFunction, minExposure (minutes), page, pageSize.
         */
        get: operations["ListBuildingRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * List rooms of a building
         * @description Filters: roomFunction, minExposure (minutes), page, pageSize.
         */
        head: operations["ListBuildingRooms"];
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a room by id */
        get: operations["GetRoomById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Get a room by id */
        head: operations["GetRoomById"];
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{roomId}/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sensors in a room
         * @description Filters: parameterCode, status, page, pageSize.
         */
        get: operations["ListRoomSensors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * List sensors in a room
         * @description Filters: parameterCode, status, page, pageSize.
         */
        head: operations["ListRoomSensors"];
        patch?: never;
        trace?: never;
    };
    "/v1/sensors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a sensor by id */
        get: operations["GetSensorById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Get a sensor by id */
        head: operations["GetSensorById"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A building's postal address, modelled on the Czech open formal standard **OFN _Adresy_** (2020-07-01, https://ofn.gov.cz/adresy/2020-07-01/) and anchored on the national address register **RÚIAN**.
         *
         *     The single field `addressPointCode` (RÚIAN *kód adresního místa*) identifies the address completely on its own; every other field is supplementary and may be null (small municipalities have no street names, an address may have no orientation number, and the RÚIAN territorial codes are filled in only when known).
         *
         *     When you request the building as Linked Data (`Accept: application/ld+json`) this object is re-shaped into a conformant OFN `Adresa` node: each `*Code` below is emitted as a **dereferenceable RÚIAN IRI** (e.g. `https://linked.cuzk.cz/resource/ruian/obec/{municipalityCode}`) and each name is carried as a Czech-language string (`{"cs": …}`). Those IRIs are stable global identifiers you can use to join this data against RÚIAN and other linked datasets.
         */
        AddressDto: {
            /**
             * Format: int64
             * @description RÚIAN address-point code (*kód adresního místa*) — the canonical, globally-unique identifier of this exact address. On its own it fully identifies the address; the remaining fields just spare a consumer a RÚIAN lookup. In JSON-LD it becomes the IRI `https://linked.cuzk.cz/resource/ruian/adresni-misto/{code}`.
             */
            addressPointCode: null | number | string;
            /** @description Street name (*název ulice*). Optional — many small municipalities have no named streets, in which case the house number alone locates the building. */
            streetName: null | string;
            /**
             * Format: int32
             * @description House number (*číslo domovní*) — the building's number within the municipality. Its exact meaning depends on `houseNumberType`.
             */
            houseNumber: null | number | string;
            /** @description Type of the house number (*typ čísla domovního*): `č.p.` = *číslo popisné* (the permanent descriptive number of a regular building) or `č.ev.` = *číslo evidenční* (a registration number used for recreational / temporary structures). */
            houseNumberType: null | string;
            /**
             * Format: int32
             * @description Orientation number (*číslo orientační*) — the street-level number used for navigation (the part after the slash in e.g. *1938/4*). Optional.
             */
            orientationNumber: null | number | string;
            /** @description Letter suffix of the orientation number (*znak čísla orientačního*), e.g. the `a` in *12a*. Optional. */
            orientationNumberLetter: null | string;
            /** @description Municipality name (*název obce*), e.g. *Praha*. */
            municipalityName: null | string;
            /** @description Name of the part of the municipality (*název části obce*), e.g. *Žižkov*. Optional. */
            municipalityPartName: null | string;
            /** @description Postal code (*PSČ*) — five digits, stored without the conventional space (e.g. `13067`, rendered as *130 67* in the free-text form). */
            psc: null | string;
            /** @description District name (*název okresu*), e.g. *Brno-město*. Optional. */
            districtName: null | string;
            /** @description Region name (*název kraje*, i.e. the VÚSC), e.g. *Jihomoravský kraj*. Optional. */
            regionName: null | string;
            /**
             * Format: int64
             * @description RÚIAN street code. When present, the JSON-LD address emits it as the dereferenceable IRI `https://linked.cuzk.cz/resource/ruian/ulice/{code}` (OFN `ulice`). Optional.
             */
            streetCode: null | number | string;
            /**
             * Format: int64
             * @description RÚIAN municipality (obec) code → JSON-LD IRI `https://linked.cuzk.cz/resource/ruian/obec/{code}` (OFN `obec`). Optional.
             */
            municipalityCode: null | number | string;
            /**
             * Format: int64
             * @description RÚIAN municipality-part code → JSON-LD IRI `https://linked.cuzk.cz/resource/ruian/cast-obce/{code}` (OFN `část_obce`). Optional.
             */
            municipalityPartCode: null | number | string;
            /**
             * Format: int64
             * @description RÚIAN district (okres) code → JSON-LD IRI `https://linked.cuzk.cz/resource/ruian/okres/{code}` (OFN `okres`). Optional.
             */
            districtCode: null | number | string;
            /**
             * Format: int64
             * @description RÚIAN region / VÚSC (kraj) code → JSON-LD IRI `https://linked.cuzk.cz/resource/ruian/vusc/{code}` (OFN `vúsc`). Optional.
             */
            regionCode: null | number | string;
        };
        AggregateBucketDto: {
            /** Format: date-time */
            t: string;
            /** Format: int64 */
            count: number | string;
            /** Format: double */
            min: number | string;
            /** Format: double */
            max: number | string;
            /** Format: double */
            avg: number | string;
            /** Format: double */
            p25: number | string;
            /** Format: double */
            p50: number | string;
            /** Format: double */
            p75: number | string;
        };
        AggregateResponse: {
            parameterCode: string;
            unit: null | string;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            bucket: string;
            buckets: components["schemas"]["AggregateBucketDto"][];
            stats: null | components["schemas"]["AggregateStatsDto"];
            license: string;
        };
        AggregateStatsDto: {
            /** Format: int64 */
            count: number | string;
            /** Format: double */
            min: number | string;
            /** Format: double */
            max: number | string;
            /** Format: double */
            avg: number | string;
            /** Format: double */
            p05: number | string;
            /** Format: double */
            p25: number | string;
            /** Format: double */
            p50: number | string;
            /** Format: double */
            p75: number | string;
            /** Format: double */
            p95: number | string;
        };
        /** @description A building in the open-data catalog, projected to its current state. `address` is the Czech OFN address (see the Address schema). `latitude`/`longitude` are the precise stored coordinates — this is open data, so they are returned in full to every reader with no anonymization. `license` (CC BY 4.0) applies to the whole response, and `iri` is the building's stable, dereferenceable identifier on this API. */
        BuildingResponse: {
            /** Format: uuid */
            id: string;
            iri: string;
            name: null | string;
            address: components["schemas"]["AddressDto"];
            buildingTypeCode: null | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: int32 */
            yearBuilt: null | number | string;
            /** Format: int32 */
            yearRenovated: null | number | string;
            license: string;
        };
        CatalogPageOfBuildingResponse: {
            items: components["schemas"]["BuildingResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            total: number | string;
            next: null | string;
            license: string;
        };
        CatalogPageOfRoomResponse: {
            items: components["schemas"]["RoomResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            total: number | string;
            next: null | string;
            license: string;
        };
        CatalogPageOfSensorResponse: {
            items: components["schemas"]["SensorResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int64 */
            total: number | string;
            next: null | string;
            license: string;
        };
        MapSnapshotItem: {
            /** Format: uuid */
            buildingId: string;
            slug: string;
            name: null | string;
            /** Format: double */
            lat: null | number | string;
            /** Format: double */
            lon: null | number | string;
            /** Format: double */
            latestValue: null | number | string;
            /** Format: date-time */
            observedAt: null | string;
            stale: boolean;
            /** Format: int32 */
            sensorCount: number | string;
        };
        MapSnapshotResponse: {
            parameterCode: string;
            unit: null | string;
            /** Format: date-time */
            asOf: string;
            items: components["schemas"]["MapSnapshotItem"][];
            license: string;
        };
        MeasuredParameterDto: {
            code: string;
            quantityKindUri: null | string;
            unitUri: null | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        PropertyCollection: {
            items: components["schemas"]["PropertyResponse"][];
            license: string;
        };
        PropertyResponse: {
            code: string;
            iri: string;
            label: string;
            quantityKindUri: null | string;
            unitUri: null | string;
            exactMatchIri: null | string;
            closeMatchIri: null | string;
            license: string;
        };
        RoomResponse: {
            /** Format: uuid */
            id: string;
            iri: string;
            /** Format: uuid */
            buildingId: string;
            name: null | string;
            /** Format: uint8 */
            floor: number | string;
            functionCode: null | string;
            exposureCode: null | string;
            /** Format: double */
            areaM2: null | number | string;
            /** Format: double */
            ceilingHeightM: null | number | string;
            ventilationType: null | string;
            pollutionSources: string[];
            license: string;
        };
        SensorResponse: {
            /** Format: uuid */
            id: string;
            iri: string;
            /** Format: uuid */
            buildingId: string;
            /** Format: uuid */
            roomId: string;
            manufacturer: null | string;
            model: null | string;
            serialNumber: null | string;
            statusCode: null | string;
            measuredParameters: components["schemas"]["MeasuredParameterDto"][];
            license: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AggregateObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AggregateObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ExportObservationsCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExportObservationsCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMeasurementsContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMeasurementsContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDcatCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDcatCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetObservationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetObservationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMapSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapSnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMapSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapSnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyCollection"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyCollection"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPropertyByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPropertyByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListCodelists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListCodelists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCodelistScheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheme: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCodelistScheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheme: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCodelistConcept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheme: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCodelistConcept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheme: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPageOfBuildingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPageOfBuildingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetBuildingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetBuildingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListBuildingRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPageOfRoomResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListBuildingRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPageOfRoomResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRoomById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRoomById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListRoomSensors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPageOfSensorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListRoomSensors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPageOfSensorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSensorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSensorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
